apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
data:
  MONGO_CONN_STR: mongodb://mongo-db:27017/devops_project
  USE_DB_AUTH: "true"
  REACT_APP_BACKEND_URL: http://localhost:8080/api/tasks